### PR TITLE
WIP: Refactor package by feature

### PR DESCRIPTION
**Pull request by einaru**
Work in progress. Feedback wanted 😄

### CODE REVIEW

**Review by olaplassen — COMMENTED** [review]
Good base, the `spell` package seemed a bit big but perhaps it doesnt matter .. Could factor out `Element` as its own if we were to change it.

**Review by olaplassen — COMMENTED** [review]
If we refactor by feature, should the "LoginMenuScreen" be in the `user`  package or `menu`  package?

**Comment by cherrybeans** [comment]
> If we refactor by feature, should the "LoginMenuScreen" be in the `user` package or `menu` package?

I'd say in the menu package

**Review by cherrybeans — APPROVED** [review]
I think it looks pretty good! Like commented above, I think based on the name and function, the LoginMenuScreen should be in the menu package, but either or works for me.

**Comment by einaru** [comment]
I can agree on moving the `LoginMenuScreen` to the menu package. If so I would argue to move `InputDialog` from user to menu as well.

**Comment by cherrybeans** [comment]
I get the feeling that some of the stuff in the spell package could in reality also be put in the game package, since it feels like it is mainly the name that puts it in the spell package, like SpellLockState. Since it feels like it is more related to the gameplay than the spell itself. However that is up for discussion. Disclaimer: I havent really looked at the detailed content of those files though, and I think it really doesn't matter

**Comment by einaru** [comment]
> I get the feeling that some of the stuff in the spell package could in reality also be put in the game package, since it feels like it is mainly the name that puts it in the spell package, like SpellLockState. Since it feels like it is more related to the gameplay than the spell itself. However that is up for discussion

Yes, there are probably some cases like that. The spell package was so massive to begin with that I didn't want to enter that rabbit hole at this point 😅 

I think it looks a lot better with these changes at least.

**Pull request merged**
